name: Basic Docker Build

on:
  push:
    branches:
      - main
    pull_request:
  
jobs:
  build-image:
    name: Build Image Action
    runs-on: ubuntu-latest
    steps:

      - name: Docker Hub Logina
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          tags: patrykmitura/docker-ci-automotion-git-actions:latest,patrykmitura/docker-ci-automotion-git-actions:01
          push: ${{ github.event_name != 'pull_request' }}
          