name: Basic Docker Build with BuildKit Cache

on:
  push:
    branches:
      - main
    pull_request:
  
jobs:
  build-image:
    name: Build Image Action
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: patrykmitura/docker-ci-automotion-git-actions:02
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7