name: Basic Docker Build with MetaData

on:
  push:
    branches:
      - main
    pull_request:
  
jobs:
  build-image:
    name: Build Image Action
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata
        uses: docker/metadata-action@v4
        with:
          images: patrykmitura/docker-ci-automotion-git-actions
          flavor: |
            latest=false
          tags:
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}
         
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7